- name: Creating nfs export directories
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Creating /etc/exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  # The notification event will be sended to 
  # the handler with the corresponding name 
  # in the handlers folder
  notify: reload_nfs

- name: Start nfs service.
  service: "name=nfs-kernel-server state=started enabled=yes"
  when: nfs_exports|length

- name: Create a master MPI user
  user:
    name: "{{ mpi_user_name }}"
    password: "{{ mpi_user_name | password_hash('sha512') }}"
    state: present
    shell: /bin/bash       
    system: no             
    createhome: yes        
    home: /home/{{ mpi_user_name }}
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
  tags:
    - user

- name: Create authorized_keys file
  file:
    path: /home/{{ mpi_user_name }}/.ssh/authorized_keys
    owner: "{{ mpi_user_name }}"
    group: "{{ mpi_user_name }}"
    mode: 0600
    state: touch
  tags:
    - pass

- name: Place public key into authorized_keys
  shell: cat /home/{{ mpi_user_name }}/.ssh/id_rsa.pub >> /home/{{ mpi_user_name }}/.ssh/authorized_keys
  tags:
    - pass

# This is necesary because ansible create the home directory with 
# root as group and owner. So we need MPI user be the group and owner
- name: Change MPI user home dir permissions
  shell: chown {{ mpi_user_name }}:{{ mpi_user_name }} /home/{{ mpi_user_name }}
